### ISSUE TITLE
4D tensors expect 4 values for padding

### ISSUE THREAD

**Issue by liuziyuan827** [Xu-Justin/DeepFaceDrawing#3]
I run you project ,but I meet a problem ,the train_stage_1.py have a erro:
![image](https://user-images.githubusercontent.com/66998346/185778578-965db624-3492-4284-bffe-c6cec69b9dd5.png)
can you update the project again? Thank you very much ,I also can paid for it.
my email :516807971@qq.com

**Comment by Xu-Justin** [comment]
Hi @liuziyuan827, I tried running the code and couldn't reproduce the error. Could you provide more information? Did you modify any parts of the code? What is the version of the torch you are using?
