### ISSUE TITLE
AssertionError: 4D tensors expect 4 values for padding

### ISSUE THREAD

**Issue by fc2635540954** [Xu-Justin/DeepFaceDrawing#4]
AssertionError: 4D tensors expect 4 values for padding
How to solve this problem？
 Thanks！

**Comment by fc2635540954** [comment]
I haven't modified the code
torch=1.8.1

**Comment by Xu-Justin** [comment]
Hi @fc2635540954, could you provide the full logs? I couldn't recreate the error.
